http_server:
  address: localhost:9000
  timeout: 15s
  idle_timeout: 60s
jt: 
  visualizer_path: 'C:\Program Files\Siemens\Teamcenter2412\Visualization\Program'
  xml_storage_path: 'C:\pmi\xml'
  js_storage_path: 'C:\pmi\jt'
  db_path: 'C:\pmi\db'